package com.dahai.yourprofile.models;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dahai.yourprofile.models.Profile;

import com.dahai.yourprofile.models.ProfileDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig profileDaoConfig;

    private final ProfileDao profileDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        profileDaoConfig = daoConfigMap.get(ProfileDao.class).clone();
        profileDaoConfig.initIdentityScope(type);

        profileDao = new ProfileDao(profileDaoConfig, this);

        registerDao(Profile.class, profileDao);
    }
    
    public void clear() {
        profileDaoConfig.getIdentityScope().clear();
    }

    public ProfileDao getProfileDao() {
        return profileDao;
    }

}
