package com.dahai.yourprofile.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PROFILE.
 */
public class Profile {

    private Long id;
    /** Not-null value. */
    private String title;
    private Short startHour;
    private Short startMinute;
    private Short startTotalMinute;
    private Integer daysOfWeek;
    private Boolean enabled;
    private Integer audioModel;

    public Profile() {
    }

    public Profile(Long id) {
        this.id = id;
    }

    public Profile(Long id, String title, Short startHour, Short startMinute, Short startTotalMinute, Integer daysOfWeek, Boolean enabled, Integer audioModel) {
        this.id = id;
        this.title = title;
        this.startHour = startHour;
        this.startMinute = startMinute;
        this.startTotalMinute = startTotalMinute;
        this.daysOfWeek = daysOfWeek;
        this.enabled = enabled;
        this.audioModel = audioModel;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public Short getStartHour() {
        return startHour;
    }

    public void setStartHour(Short startHour) {
        this.startHour = startHour;
    }

    public Short getStartMinute() {
        return startMinute;
    }

    public void setStartMinute(Short startMinute) {
        this.startMinute = startMinute;
    }

    public Short getStartTotalMinute() {
        return startTotalMinute;
    }

    public void setStartTotalMinute(Short startTotalMinute) {
        this.startTotalMinute = startTotalMinute;
    }

    public Integer getDaysOfWeek() {
        return daysOfWeek;
    }

    public void setDaysOfWeek(Integer daysOfWeek) {
        this.daysOfWeek = daysOfWeek;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public Integer getAudioModel() {
        return audioModel;
    }

    public void setAudioModel(Integer audioModel) {
        this.audioModel = audioModel;
    }

}
